import React, { useEffect, useState } from "react";
import { api } from "../api.js";
import { go } from "../App.jsx";
import { useT } from "../i18n.js";

const KIND_LABEL = {
  "spike": "Spike alerts",
  "emerging-trend": "Emerging trends",
  "anomaly": "Anomalies",
};

export default function AlertsView() {
  const t = useT();
  const [alerts, setAlerts] = useState(null);
  const [kind, setKind] = useState("");
  const [brief, setBrief] = useState(null);      // null | "busy" | {markdown..}

  useEffect(() => {
    api(`/api/alerts${kind ? `?kind=${kind}` : ""}`)
      .then((r) => setAlerts(r.alerts)).catch(console.error);
  }, [kind]);

  async function makeBrief(alertId) {
    setBrief("busy");
    try {
      setBrief(await api("/api/brief", {
        method: "POST", json: { alert_id: alertId },
      }));
    } catch (e) {
      setBrief({ markdown: `Error: ${e}`, evidence: [] });
    }
  }

  if (!alerts) return <div className="loading">Loading alerts…</div>;

  if (brief) {
    return (
      <div className="pad" style={{ maxWidth: 860, margin: "0 auto" }}>
        <a className="backlink" onClick={() => setBrief(null)}>← back to alerts</a>
        {brief === "busy"
          ? <div className="loading">The monitoring agent is drafting the brief…</div>
          : <div className="card" id="brief-print">
              <h3>Intelligence brief — {brief.scope} · as of {brief.as_of}</h3>
              <div style={{ whiteSpace: "pre-wrap", lineHeight: 1.7 }}>
                {brief.markdown}
              </div>
              <div style={{ marginTop: 12 }}>
                {(brief.evidence || []).slice(0, 15).map((cn) => (
                  <span key={cn} className="chip mono accent rowlink"
                        onClick={() => go(`/case/${cn}`)}>{cn}</span>
                ))}
              </div>
              <button className="chip accent"
                      style={{ marginTop: 12, cursor: "pointer", fontSize: 13 }}
                      onClick={() => window.print()}>
                Save as PDF (print)
              </button>
            </div>}
      </div>
    );
  }

  const groups = {};
  alerts.forEach((a) => (groups[a.kind] = groups[a.kind] || []).push(a));

  return (
    <div className="pad">
      <h2 className="pagetitle">{t("alerts.title")}
        <span className="muted" style={{ fontSize: 13, marginLeft: 10 }}>
          generated by the monitoring engine — every alert carries its evidence
        </span>
      </h2>
      <div className="filters">
        <select value={kind} onChange={(e) => setKind(e.target.value)}>
          <option value="">All kinds</option>
          <option value="spike">Spikes</option>
          <option value="emerging-trend">Emerging trends</option>
          <option value="anomaly">Anomalies</option>
        </select>
        <span className="muted">{alerts.length} active</span>
      </div>
      {Object.entries(groups).map(([k, list]) => (
        <div key={k}>
          <h3 style={{ color: "var(--muted)", textTransform: "uppercase",
                       fontSize: 12, letterSpacing: 1 }}>
            {KIND_LABEL[k] || k} ({list.length})
          </h3>
          {list.slice(0, 40).map((a) => (
            <div key={a.alert_id} className={`card alert-card ${a.kind}`}>
              <div>{a.summary}
                <a style={{ float: "right", fontSize: 12 }}
                   onClick={() => makeBrief(a.alert_id)}>{t("alerts.brief")} →</a>
              </div>
              <div className="z" style={{ margin: "6px 0" }}>
                {a.zscore != null && <>z = {a.zscore} · </>}
                observed {a.observed}{a.baseline ? ` vs baseline ${a.baseline}` : ""}
                {a.window_start && <> · {a.window_start} → {a.window_end}</>}
              </div>
              <div>
                {a.evidence.slice(0, 8).map((cn) => (
                  <span key={cn} className="chip mono accent rowlink"
                        onClick={() => go(`/case/${cn}`)}>{cn}</span>
                ))}
                {a.evidence_count > 8 && (
                  <span className="chip">+{a.evidence_count - 8} more</span>
                )}
              </div>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}
